// @ts-nocheck -- DOM event targets are validated by the rendered form markup.
import { createClient, type Session, type SupabaseClient } from '@supabase/supabase-js'
import { Capacitor, registerPlugin } from '@capacitor/core'
import { LocalNotifications } from '@capacitor/local-notifications'

type Config = { url: string; key: string }
type Task = Record<string, any>
type Project = Record<string, any>
type Review = Record<string, any>
type Inbox = Record<string, any>
type ReleaseManifest = { version:string; channel:'stable'|'preview'; release_notes:string; published_at:string; desktop:{url:string;sha256:string}; android:{url:string;sha256:string;min_supported_version:string} }
const APP_VERSION = '2.2.0'
const YanXuUpdater = registerPlugin<{ downloadAndInstall(options:{url:string;sha256:string}):Promise<{status:string}> }>('YanXuUpdater')
const app = document.querySelector<HTMLDivElement>('#app')!
let config: Config | null = readConfig(), db: SupabaseClient | null = null, session: Session | null = null, space: any = null
let tasks: Task[] = [], projects: Project[] = [], milestones: any[] = [], reviews: Review[] = [], inbox: Inbox[] = [], focus: any[] = [], page = 'today'
let focusStarted: Date | null = null, focusTask: string | null = null, focusTimer = 0
let latestUpdate: ReleaseManifest | null = null, startupUpdateChecked = false
const date = () => new Date().toISOString().slice(0, 10)
const esc = (x: any) => String(x ?? '').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')
const me = () => session!.user.id
function readConfig() { try { return JSON.parse(localStorage.getItem('yanxu-supabase') || localStorage.getItem('focus-supabase') || 'null') } catch { return null } }
function notice(text = '') { const node = document.querySelector<HTMLElement>('[data-error]'); if (node) { node.textContent = text; node.hidden = !text } }

const versionParts = (value:string) => value.replace(/^v/, '').split('.').map(x => Number(x))
function newerThan(candidate:string, current:string) { const a=versionParts(candidate), b=versionParts(current); return [0,1,2].some(i => (a[i]||0)!==(b[i]||0) && (a[i]||0)>(b[i]||0) && a.slice(0,i).every((x,j)=>x===(b[j]||0))) }
const updateAuto = () => localStorage.getItem('yanxu-update-auto') !== 'false'
const updateChannel = () => localStorage.getItem('yanxu-update-channel') || 'stable'
const manifestUrl = () => `${config!.url.replace(/\/$/, '')}/storage/v1/object/public/yanxu-releases/manifest.json`

async function checkForUpdates(silent = false) {
  const state = document.querySelector<HTMLElement>('#update-state'); if (state) state.textContent = '正在检查…'
  try {
    const response = await fetch(manifestUrl(), { cache:'no-store', headers:{'Cache-Control':'no-cache'} })
    if (!response.ok) throw new Error(`HTTP ${response.status}`)
    const manifest = await response.json() as ReleaseManifest
    if (!/^\d+\.\d+\.\d+$/.test(manifest.version) || !['stable','preview'].includes(manifest.channel)) throw new Error('版本清单格式无效')
    if (!manifest.android?.url?.startsWith('https://') || !/^[0-9a-f]{64}$/i.test(manifest.android.sha256)) throw new Error('Android 下载地址或 SHA-256 无效')
    if (updateChannel() === 'stable' && manifest.channel !== 'stable') {
      latestUpdate = null; updateStatus(`稳定版通道暂无更新 · v${APP_VERSION}`, '暂无更新说明'); return null
    }
    if (newerThan(manifest.version, APP_VERSION)) {
      latestUpdate = manifest; updateStatus(`发现新版本 v${manifest.version}`, manifest.release_notes || '暂无更新说明'); showUpdatePrompt(manifest); return manifest
    }
    latestUpdate = null; updateStatus(`已是最新版本 v${APP_VERSION}`, '暂无更新说明')
    if (!silent) alert(`当前已是最新版本 v${APP_VERSION}`)
    return null
  } catch (error:any) {
    updateStatus('检查更新失败', error?.message || String(error))
    if (!silent) alert(`无法检查更新：${error?.message || error}`)
    return null
  }
}
function updateStatus(status:string, notes:string) {
  const state=document.querySelector<HTMLElement>('#update-state'), copy=document.querySelector<HTMLElement>('#update-notes'), button=document.querySelector<HTMLButtonElement>('#install-update')
  if(state) state.textContent=status; if(copy) copy.textContent=notes; if(button) button.hidden=!latestUpdate
}
function showUpdatePrompt(manifest:ReleaseManifest) {
  document.querySelector('#update-dialog')?.remove()
  document.body.insertAdjacentHTML('beforeend', `<div class="update-dialog" id="update-dialog"><section><div class="brand-kicker">系统更新</div><h2>研序 v${esc(manifest.version)}</h2><p>${esc(manifest.release_notes || '暂无更新说明')}</p><div class="split"><button class="secondary" id="update-later">稍后</button><button class="primary" id="update-now">立即更新</button></div></section></div>`)
  document.querySelector('#update-later')!.addEventListener('click',()=>document.querySelector('#update-dialog')?.remove())
  document.querySelector('#update-now')!.addEventListener('click',()=>{document.querySelector('#update-dialog')?.remove();void installLatestUpdate()})
}
async function installLatestUpdate() {
  if (!latestUpdate) return void checkForUpdates(false)
  if (!Capacitor.isNativePlatform()) return alert('请在 Android 应用中安装更新。')
  updateStatus(`正在下载 v${latestUpdate.version}…`, latestUpdate.release_notes || '')
  try {
    const result = await YanXuUpdater.downloadAndInstall({url:latestUpdate.android.url,sha256:latestUpdate.android.sha256})
    if (result.status === 'permission_required') alert('请在系统页面允许“安装未知应用”，返回研序后再次点击“立即更新”。')
    else updateStatus('安装器已打开', '请在 Android 系统安装器中确认更新。')
  } catch (error:any) { updateStatus('更新失败，当前版本未改变', error?.message || String(error)); alert(error?.message || String(error)) }
}

export async function bootYanXu() {
  if (!config?.url || !config?.key) return configView()
  db = createClient(config.url, config.key, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: false } })
  db.auth.onAuthStateChange((_e, next) => { session = next; void route() })
  await route()
  if (!startupUpdateChecked && updateAuto()) { startupUpdateChecked = true; void checkForUpdates(true) }
}
async function route() {
  if (!db) return
  session = (await db.auth.getSession()).data.session
  if (!session) return authView()
  const r = await db.from('space_members').select('space_id,spaces(id,name,invite_code)').eq('user_id', me()).limit(1).maybeSingle()
  space = r.data?.spaces || null
  if (!space) return spaceView()
  await load(); render()
}
function configView() {
  app.innerHTML = `<main class="screen-center"><section class="auth-card"><div class="brand-kicker">研序 · YanXu</div><h1>连接学习工作台</h1><p>同一账号在电脑与手机间同步；可邀请一位成员进入共享空间。</p><div class="error" data-error hidden></div><form id="config"><div class="field"><label>Supabase Project URL</label><input name="url" type="url" required></div><div class="field"><label>Publishable key</label><textarea name="key" required></textarea></div><button class="primary wide">保存并连接</button></form></section></main>`
  document.querySelector<HTMLFormElement>('#config')!.onsubmit = e => { e.preventDefault(); const f = new FormData(e.currentTarget); config = { url: String(f.get('url')).trim().replace(/\/$/, ''), key: String(f.get('key')).trim() }; if (!config.url.includes('.supabase.co')) return notice('Project URL 不正确。'); localStorage.setItem('yanxu-supabase', JSON.stringify(config)); void bootYanXu() }
}
function authView() {
  app.innerHTML = `<main class="screen-center"><section class="auth-card"><div class="brand-kicker">研序 · YanXu</div><h1>欢迎回来</h1><p>个人学习数据随账号在所有设备同步。</p><div class="error" data-error hidden></div><form id="auth"><div class="field"><label>称呼（注册用）</label><input name="name"></div><div class="field"><label>邮箱</label><input name="email" type="email" required></div><div class="field"><label>密码</label><input name="password" type="password" minlength="6" required></div><div class="split"><button class="primary" name="action" value="login">登录</button><button class="secondary" name="action" value="signup">注册</button></div></form></section></main>`
  document.querySelector<HTMLFormElement>('#auth')!.onsubmit = async e => { e.preventDefault(); const f = new FormData(e.currentTarget), submit = (e as SubmitEvent).submitter as HTMLButtonElement, email = String(f.get('email')).trim(), password = String(f.get('password')); const r = submit.value === 'signup' ? await db!.auth.signUp({ email, password, options: { data: { display_name: String(f.get('name') || email.split('@')[0]) } } }) : await db!.auth.signInWithPassword({ email, password }); if (r.error) notice(r.error.message); else if (submit.value === 'signup' && !r.data.session) notice('请完成邮箱验证后登录。') }
}
function spaceView() {
  app.innerHTML = `<main class="screen-center"><section class="auth-card"><div class="brand-kicker">研序 · YanXu</div><h1>创建或加入空间</h1><p>任务和项目在空间内共享；复习、专注和 Inbox 仅自己可见。</p><div class="error" data-error hidden></div><form id="create"><div class="field"><label>称呼</label><input name="name" required></div><div class="field"><label>空间名称</label><input name="space" value="我们的研序" required></div><button class="primary wide">创建空间</button></form><div class="divider">或者</div><form id="join"><div class="field"><label>称呼</label><input name="name" required></div><div class="field"><label>邀请码</label><input name="code" maxlength="8" required></div><button class="secondary wide">加入空间</button></form></section></main>`
  document.querySelector<HTMLFormElement>('#create')!.onsubmit = async e => { e.preventDefault(); const f = new FormData(e.currentTarget); const r = await db!.rpc('create_couple_space', { space_name: String(f.get('space')), member_name: String(f.get('name')) }); if (r.error) notice(r.error.message); else void route() }
  document.querySelector<HTMLFormElement>('#join')!.onsubmit = async e => { e.preventDefault(); const f = new FormData(e.currentTarget); const r = await db!.rpc('join_couple_space', { code: String(f.get('code')), member_name: String(f.get('name')) }); if (r.error) notice(r.error.message); else void route() }
}
async function load() {
  const q = await Promise.all([
    db!.from('tasks').select('*').eq('space_id', space.id).is('deleted_at', null).order('updated_at', { ascending: false }),
    db!.from('projects').select('*').eq('space_id', space.id).is('deleted_at', null).order('updated_at', { ascending: false }),
    db!.from('milestones').select('*').is('deleted_at', null),
    db!.from('reviews').select('*').eq('owner_id', me()).is('deleted_at', null).order('next_review_at'),
    db!.from('inbox_items').select('*').eq('owner_id', me()).is('deleted_at', null).order('created_at', { ascending: false }),
    db!.from('focus_sessions').select('*').eq('owner_id', me()).is('deleted_at', null).order('started_at', { ascending: false })
  ])
  const bad = q.find(x => x.error); if (bad?.error) { app.innerHTML = `<main class="screen-center"><section class="auth-card"><h1>需要执行 V2 迁移</h1><p>${esc(bad.error.message)}</p><p>请在 Supabase SQL Editor 执行 supabase/migrations/20260811_yanxu_v2.sql。</p></section></main>`; return }
  tasks = q[0].data || []; projects = q[1].data || []; milestones = q[2].data || []; reviews = q[3].data || []; inbox = q[4].data || []; focus = q[5].data || []
  void scheduleNotifications()
}
function nav() { return `<nav class="nav">${[['today','今日'],['tasks','任务'],['projects','项目'],['reviews','复习'],['inbox','Inbox'],['calendar','日历'],['review','回顾'],['settings','设置']].map(([id,label]) => `<button class="${id === page ? 'active' : ''}" data-page="${id}">${label}</button>`).join('')}</nav>` }
function shell(content: string) { app.innerHTML = `<main class="shell"><header class="topbar"><div><div class="brand-kicker">研序 · YanXu</div><h1>Research · Learn · Progress</h1></div><button class="icon-btn" id="quick">＋</button></header>${nav()}${content}</main>`; document.querySelectorAll<HTMLButtonElement>('[data-page]').forEach(b => b.onclick = () => { page = b.dataset.page!; render() }); document.querySelector('#quick')!.onclick = () => inboxForm() }
function render() { if (page === 'today') today(); else if (page === 'tasks') taskView(); else if (page === 'projects') projectView(); else if (page === 'reviews') reviewView(); else if (page === 'inbox') inboxView(); else if (page === 'calendar') calendarView(); else if (page === 'review') weeklyView(); else settingsView() }
function taskCard(t: Task) { const p = projects.find(x => x.id === t.project_id); return `<article class="task"><div class="task-head"><div><div class="task-title">${esc(t.title)}</div><div class="task-meta">${t.all_day ? '全天' : (t.start_time || '未排时间')}${p ? ` · ${esc(p.name)}` : ''}${t.estimated_minutes ? ` · ${t.estimated_minutes} min` : ''}</div></div><div class="task-actions"><button class="icon-btn" data-edit="${t.id}">✎</button><button class="check ${t.status === 'completed' ? 'checked' : ''}" data-done="${t.id}">✓</button></div></div><div class="chips"><span class="chip">${({pending:'待开始',in_progress:'进行中',waiting:'等待',blocked:'阻塞',completed:'完成',cancelled:'取消'} as any)[t.status] || '待开始'}</span>${t.priority === 'today' ? '<span class="chip priority">今日重点</span>' : ''}</div>${t.status === 'blocked' ? `<p class="warning">阻塞：${esc(t.blocker_reason || '待处理')}</p>` : ''}</article>` }
function bindTaskCards() { document.querySelectorAll<HTMLButtonElement>('[data-done]').forEach(b => b.onclick = () => void done(b.dataset.done!)); document.querySelectorAll<HTMLButtonElement>('[data-edit]').forEach(b => b.onclick = () => taskForm(tasks.find(t => t.id === b.dataset.edit))) }
function today() { const day = tasks.filter(t => t.start_date <= date() && t.end_date >= date() && !['completed','cancelled'].includes(t.status) && (!t.assignee_id || t.assignee_id === me())), highlights = day.filter(t => ['today','high'].includes(t.priority)).slice(0,3), due = reviews.filter(r => r.is_active && r.next_review_at <= new Date().toISOString()), ps = projects.filter(p => p.status === 'active').slice(0,4), attention = tasks.filter(t => t.status === 'blocked' || (t.follow_up_at && t.follow_up_at <= new Date().toISOString())).slice(0,3)
  shell(`<section class="hero"><div class="hero-row"><div><div class="hero-date">${new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}</div><div class="hero-copy">今天先推进最重要的一步。</div></div><button class="primary" id="new-task">新建任务</button></div></section><section class="focus-bar"><span>${focusStarted ? `专注中 · ${focusElapsed()}` : '从管理切换到真正开始'}</span><button class="${focusStarted ? 'danger' : 'primary'}" id="focus-action">${focusStarted ? '结束专注' : '开始专注'}</button></section><section class="section-head"><h2>今日重点</h2></section><section class="task-list">${highlights.map(taskCard).join('') || '<div class="card empty">还没有重点。先放进最重要的一步。</div>'}</section><section class="dashboard-grid"><article class="card"><h3>待复习</h3><strong>${due.length} 项</strong><button class="secondary" id="go-reviews">开始复习</button></article><article class="card"><h3>Inbox</h3><strong>${inbox.filter(i => i.status === 'inbox').length} 条</strong><button class="secondary" id="go-inbox">快速捕获</button></article></section><section class="section-head"><h2>今日时间线</h2></section><section class="task-list">${day.map(taskCard).join('') || '<div class="card empty">今天没有安排。</div>'}</section><section class="section-head"><h2>长期推进</h2></section><section class="project-list">${ps.map(projectCard).join('') || '<div class="card empty">新建一个项目，让长期目标持续向前。</div>'}</section>${attention.length ? `<section class="section-head"><h2>需要关注</h2></section><section class="task-list">${attention.map(taskCard).join('')}</section>` : ''}`)
  document.querySelector('#new-task')!.onclick = () => taskForm(); document.querySelector('#go-reviews')!.onclick = () => { page = 'reviews'; render() }; document.querySelector('#go-inbox')!.onclick = () => inboxForm(); document.querySelector('#focus-action')!.onclick = () => focusStarted ? void finishFocus() : startFocus(day[0]); bindTaskCards()
}
function taskView() { shell(`<section class="page-heading"><div><h2>任务</h2><p>短期、具体、可执行的行动。</p></div><button class="primary" id="new">＋ 任务</button></section><section class="task-list">${tasks.map(taskCard).join('') || '<div class="card empty">没有任务。</div>'}</section>`); document.querySelector('#new')!.onclick = () => taskForm(); bindTaskCards() }
function projectCard(p: Project) { return `<article class="project-card" data-project="${p.id}"><div class="project-row"><strong>${esc(p.name)}</strong><span>${p.progress}%</span></div><div class="progress"><i style="width:${p.progress}%"></i></div><p>下一步：${esc(p.next_action || '尚未设置')}</p></article>` }
function projectView() { shell(`<section class="page-heading"><div><h2>项目</h2><p>目标、阶段、里程碑和下一步行动。</p></div><button class="primary" id="new">＋ 项目</button></section><section class="project-list">${projects.map(p => `${projectCard(p)}<div class="milestones">${milestones.filter(m => m.project_id === p.id).map(m => `<button class="milestone" data-milestone="${m.id}">${m.status === 'completed' ? '✓' : '○'} ${esc(m.title)}</button>`).join('')}<button class="link-btn" data-add-milestone="${p.id}">＋ 里程碑</button></div>`).join('') || '<div class="card empty">把长期目标拆成可推进的项目。</div>'}</section>`); document.querySelector('#new')!.onclick = () => projectForm(); document.querySelectorAll<HTMLElement>('[data-project]').forEach(x => x.onclick = () => projectForm(projects.find(p => p.id === x.dataset.project))); document.querySelectorAll<HTMLButtonElement>('[data-milestone]').forEach(b => b.onclick = () => void milestoneDone(b.dataset.milestone!)); document.querySelectorAll<HTMLButtonElement>('[data-add-milestone]').forEach(b => b.onclick = () => milestoneForm(b.dataset.addMilestone!)) }
function reviewView() { const due = reviews.filter(r => r.is_active && r.next_review_at <= new Date().toISOString()); shell(`<section class="page-heading"><div><h2>强化复习</h2><p>只为需要反复强化的知识服务。</p></div><button class="primary" id="new">＋ 复习</button></section><section class="task-list">${due.map(reviewCard).join('') || '<div class="card empty">今天没有到期复习。</div>'}</section><section class="section-head"><h2>后续</h2></section><section class="task-list">${reviews.filter(r => !due.includes(r)).map(reviewCard).join('')}</section>`); document.querySelector('#new')!.onclick = () => reviewForm(); document.querySelectorAll<HTMLButtonElement>('[data-rate]').forEach(b => b.onclick = () => void rate(b.dataset.rate!, b.dataset.value!)) }
function reviewCard(r: Review) { return `<article class="task"><div class="task-title">${esc(r.title)}</div><div class="task-meta">下次：${new Date(r.next_review_at).toLocaleString('zh-CN')}</div><p>${esc(r.note)}</p><div class="rating">${[['forgot','忘了'],['vague','模糊'],['remembered','记得'],['mastered','熟悉']].map(([v,l]) => `<button data-rate="${r.id}" data-value="${v}">${l}</button>`).join('')}</div></article>` }
function inboxView() { shell(`<section class="page-heading"><div><h2>Inbox</h2><p>先捕获，再整理。</p></div><button class="primary" id="new">＋ 记录</button></section><section class="task-list">${inbox.filter(i => i.status === 'inbox').map(i => `<article class="task"><div class="task-title">${esc(i.content)}</div><div class="rating"><button data-convert="task" data-id="${i.id}">转任务</button><button data-convert="review" data-id="${i.id}">转复习</button><button data-dismiss="${i.id}">忽略</button></div></article>`).join('') || '<div class="card empty">想到什么先记下来，不必现在整理。</div>'}</section>`); document.querySelector('#new')!.onclick = () => inboxForm(); document.querySelectorAll<HTMLButtonElement>('[data-convert]').forEach(b => b.onclick = () => void convertInbox(b.dataset.id!,b.dataset.convert!)); document.querySelectorAll<HTMLButtonElement>('[data-dismiss]').forEach(b => b.onclick = () => void softDelete('inbox_items',b.dataset.dismiss!)) }
function calendarView() { const todayTasks = tasks.filter(t => t.start_date === date()); shell(`<section class="page-heading"><div><h2>日历</h2><p>日历负责时间分布，今日负责行动。</p></div></section><section class="card"><h3>今天 · ${date()}</h3>${todayTasks.map(taskCard).join('') || '<p>今天没有时间安排。</p>'}</section>`); bindTaskCards() }
function weeklyView() { const mins = focus.reduce((s,x) => s + (x.duration_minutes || 0), 0), complete = tasks.filter(t => t.status === 'completed').length; shell(`<section class="page-heading"><div><h2>周回顾</h2><p>关注推进和投入，不做打卡压力。</p></div></section><section class="dashboard-grid"><article class="card"><h3>完成</h3><strong>${complete} 项</strong></article><article class="card"><h3>专注</h3><strong>${Math.floor(mins/60)}h ${mins%60}m</strong></article><article class="card"><h3>复习</h3><strong>${reviews.length} 项</strong></article></section><section class="card"><form id="weekly"><div class="field"><label>本周推进与下周三项重点</label><textarea name="highlights"></textarea></div><button class="primary">保存回顾</button></form></section>`); document.querySelector<HTMLFormElement>('#weekly')!.onsubmit = async e => { e.preventDefault(); const f = new FormData(e.currentTarget); await db!.from('weekly_reviews').upsert({space_id:space.id,owner_id:me(),period_start:date(),highlights:String(f.get('highlights')||'')},{onConflict:'owner_id,period_start'}); alert('已保存。') } }
function settingsView() { shell(`<section class="page-heading"><div><h2>设置</h2><p>同步、通知、系统更新和账户。</p></div></section><section class="settings-list"><article class="card"><h3>同步与账户</h3><p>已连接 · ${esc(space.name)}</p><p>邀请码：<strong>${esc(space.invite_code)}</strong></p></article><article class="card"><h3>通知与复习</h3><p>手机端会根据提醒策略聚合通知。</p></article><article class="card update-card"><h3>系统更新</h3><p id="update-state">${latestUpdate?`发现新版本 v${esc(latestUpdate.version)}`:`当前版本 v${APP_VERSION}`}</p><p class="update-notes" id="update-notes">${esc(latestUpdate?.release_notes || '桌面端与 Android 共用同一份版本清单。')}</p><label class="checkbox"><input type="checkbox" id="update-auto" ${updateAuto()?'checked':''}> 自动检查更新</label><div class="field"><label>更新通道</label><select id="update-channel"><option value="stable" ${updateChannel()==='stable'?'selected':''}>稳定版</option><option value="preview" ${updateChannel()==='preview'?'selected':''}>预览版</option></select></div><div class="update-actions"><button class="secondary" id="check-update">检查更新</button><button class="primary" id="install-update" ${latestUpdate?'':'hidden'}>下载更新</button></div></article><article class="card"><button class="danger" id="logout">退出登录</button></article></section>`); document.querySelector<HTMLInputElement>('#update-auto')!.onchange=e=>localStorage.setItem('yanxu-update-auto',String(e.currentTarget.checked)); document.querySelector<HTMLSelectElement>('#update-channel')!.onchange=e=>localStorage.setItem('yanxu-update-channel',e.currentTarget.value); document.querySelector('#check-update')!.addEventListener('click',()=>void checkForUpdates(false)); document.querySelector('#install-update')!.addEventListener('click',()=>void installLatestUpdate()); document.querySelector('#logout')!.onclick = async () => { await db!.auth.signOut(); void route() } }
function modal(title:string, content:string) { document.body.insertAdjacentHTML('beforeend', `<div class="sheet-backdrop" id="sheet"><section class="sheet"><div class="sheet-title"><h2>${title}</h2><button class="icon-btn" id="close">×</button></div><div class="error" data-error hidden></div>${content}</section></div>`); document.querySelector('#close')!.onclick = close; document.querySelector('#sheet')!.addEventListener('click',e => { if(e.target === e.currentTarget) close() }) }
function close() { document.querySelector('#sheet')?.remove() }
function taskForm(t?:Task) { modal(t?'编辑任务':'新建任务', `<form id="form"><div class="field"><label>任务是什么？</label><input name="title" required value="${esc(t?.title)}"></div><div class="split"><div class="field"><label>日期</label><input name="start" type="date" value="${t?.start_date||date()}"></div><div class="field"><label>时间</label><input name="time" type="time" value="${(t?.start_time||'').slice(0,5)}"></div></div><div class="split"><div class="field"><label>预计分钟</label><input name="minutes" type="number" min="1" value="${t?.estimated_minutes||''}"></div><div class="field"><label>项目</label><select name="project"><option value="">不关联</option>${projects.filter(p=>p.status==='active').map(p=>`<option value="${p.id}" ${p.id===t?.project_id?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div></div><details><summary>更多设置</summary><div class="field"><label>状态</label><select name="status">${['pending','in_progress','waiting','blocked','completed','cancelled'].map(s=>`<option ${s===(t?.status||'pending')?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>优先级</label><select name="priority">${['low','normal','high','today'].map(s=>`<option ${s===(t?.priority||'normal')?'selected':''}>${s}</option>`).join('')}</select></div><div class="field"><label>提醒时间</label><input name="reminder" type="datetime-local" value="${t?.reminder_at?.slice(0,16)||''}"></div><div class="field"><label>重复规则</label><select name="repeat"><option value="none">不重复</option><option value="daily">每天</option><option value="weekdays">工作日</option><option value="weekly">每周</option></select></div><div class="field"><label>下一次跟进</label><input name="follow" type="datetime-local" value="${t?.follow_up_at?.slice(0,16)||''}"></div><div class="field"><label>阻塞原因</label><input name="blocker" value="${esc(t?.blocker_reason)}"></div><label class="checkbox"><input type="checkbox" name="review" ${t?.review_enabled?'checked':''}> 完成后加入复习</label><div class="field"><label>备注</label><textarea name="description">${esc(t?.description)}</textarea></div></details><div class="sheet-actions">${t?'<button class="danger" type="button" id="delete">删除</button>':''}<button class="secondary" type="button" id="cancel">取消</button><button class="primary">保存</button></div></form>`); document.querySelector('#cancel')!.onclick=close; document.querySelector<HTMLFormElement>('#form')!.onsubmit=e=>void saveTask(e,t); document.querySelector('#delete')?.addEventListener('click',()=>void softDelete('tasks',t.id)) }
async function saveTask(e:SubmitEvent, old?:Task) { e.preventDefault(); const f=new FormData(e.currentTarget as HTMLFormElement), d=String(f.get('start')||date()), reminder=f.get('reminder')?new Date(String(f.get('reminder'))).toISOString():null, repeat=String(f.get('repeat')||'none'), payload:any={space_id:space.id,creator_id:old?.creator_id||me(),title:String(f.get('title')).trim(),description:String(f.get('description')||''),start_date:d,end_date:d,start_time:String(f.get('time')||'')||null,end_time:null,all_day:!f.get('time'),status:String(f.get('status')),priority:String(f.get('priority')),project_id:String(f.get('project')||'')||null,estimated_minutes:Number(f.get('minutes'))||null,reminder_at:reminder,reminder_policy:reminder?{enabled:true,at:reminder,channels:['system','in_app']}:{},repeat_rule:repeat==='none'?{}:{frequency:repeat},follow_up_at:f.get('follow')?new Date(String(f.get('follow'))).toISOString():null,blocker_reason:String(f.get('blocker')||''),review_enabled:f.get('review')==='on'}; const r=old?await db!.from('tasks').update(payload).eq('id',old.id):await db!.from('tasks').insert(payload); if(r.error)return notice(r.error.message); close();await load();render() }
async function done(id:string) { const t=tasks.find(x=>x.id===id)!, status=t.status==='completed'?'pending':'completed'; await db!.from('tasks').update({status}).eq('id',id); if(status==='completed'&&t.review_enabled) await db!.from('reviews').insert({space_id:space.id,owner_id:me(),source_task_id:id,title:t.title,note:t.description,next_review_at:new Date().toISOString()}); await load();render() }
function projectForm(p?:Project) { modal(p?'编辑项目':'新建项目',`<form id="form"><div class="field"><label>名称</label><input name="name" required value="${esc(p?.name)}"></div><div class="field"><label>目标</label><textarea name="goal">${esc(p?.goal)}</textarea></div><div class="field"><label>下一步行动</label><input name="next" value="${esc(p?.next_action)}"></div><div class="split"><div class="field"><label>进度</label><input name="progress" type="number" min="0" max="100" value="${p?.progress||0}"></div><div class="field"><label>截止</label><input name="due" type="date" value="${p?.due_at||''}"></div></div><div class="sheet-actions">${p?'<button class="danger" type="button" id="delete">删除</button>':''}<button class="secondary" type="button" id="cancel">取消</button><button class="primary">保存</button></div></form>`);document.querySelector('#cancel')!.onclick=close;document.querySelector<HTMLFormElement>('#form')!.onsubmit=e=>void saveProject(e,p);document.querySelector('#delete')?.addEventListener('click',()=>void softDelete('projects',p.id)) }
async function saveProject(e:SubmitEvent,old?:Project){e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement),value:any={space_id:space.id,owner_id:old?.owner_id||me(),name:String(f.get('name')).trim(),goal:String(f.get('goal')||''),next_action:String(f.get('next')||''),progress:Number(f.get('progress'))||0,due_at:String(f.get('due')||'')||null,status:old?.status||'active',visibility:'shared'};const r=old?await db!.from('projects').update(value).eq('id',old.id):await db!.from('projects').insert(value);if(r.error)return notice(r.error.message);close();await load();render()}
function milestoneForm(projectId:string){modal('新增里程碑',`<form id="form"><div class="field"><label>里程碑</label><input name="title" required></div><button class="primary">保存</button></form>`);document.querySelector<HTMLFormElement>('#form')!.onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await db!.from('milestones').insert({project_id:projectId,title:String(f.get('title')).trim()});close();await load();render()}}
async function milestoneDone(id:string){const m=milestones.find(x=>x.id===id);await db!.from('milestones').update({status:m.status==='completed'?'pending':'completed'}).eq('id',id);await load();render()}
function reviewForm(){modal('新建复习',`<form id="form"><div class="field"><label>复习内容</label><input name="title" required></div><div class="field"><label>提示</label><textarea name="note"></textarea></div><button class="primary">加入复习</button></form>`);document.querySelector<HTMLFormElement>('#form')!.onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await db!.from('reviews').insert({space_id:space.id,owner_id:me(),title:String(f.get('title')).trim(),note:String(f.get('note')||''),next_review_at:new Date().toISOString()});close();await load();render()}}
async function rate(id:string,value:string){const r=reviews.find(x=>x.id===id),intervals=r.intervals||[1,2,4,7,15,30];let step=r.current_step||0;if(value==='forgot')step=0;else if(value==='vague')step=Math.max(0,step-1);else step+=value==='mastered'?2:1;const next=new Date();next.setDate(next.getDate()+intervals[Math.min(step,intervals.length-1)]);await db!.from('review_logs').insert({review_id:id,owner_id:me(),rating:value});await db!.from('reviews').update({current_step:step,last_rating:value,next_review_at:next.toISOString()}).eq('id',id);await load();render()}
function inboxForm(){modal('快速捕获',`<form id="form"><div class="field"><label>想到什么先记下来</label><textarea name="content" required></textarea></div><button class="primary">保存到 Inbox</button></form>`);document.querySelector<HTMLFormElement>('#form')!.onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await db!.from('inbox_items').insert({space_id:space.id,owner_id:me(),content:String(f.get('content')).trim()});close();await load();render()}}
async function convertInbox(id:string,kind:string){const i=inbox.find(x=>x.id===id),r=kind==='task'?await db!.from('tasks').insert({space_id:space.id,creator_id:me(),title:i.content,description:'',start_date:date(),end_date:date(),all_day:true,status:'pending',priority:'normal'}).select('id').single():await db!.from('reviews').insert({space_id:space.id,owner_id:me(),title:i.content,next_review_at:new Date().toISOString()}).select('id').single();if(r.error)return;await db!.from('inbox_items').update({status:'converted',converted_type:kind,converted_id:r.data.id}).eq('id',id);await load();render()}
async function softDelete(table:string,id:string){if(!confirm('确认删除？将同步到所有设备。'))return;await db!.from(table).update({deleted_at:new Date().toISOString()}).eq('id',id);close();await load();render()}
function focusElapsed(){if(!focusStarted)return'00:00';const seconds=Math.floor((Date.now()-focusStarted.getTime())/1000);return`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}
function startFocus(task?:Task){focusStarted=new Date();focusTask=task?.id||null;focusTimer=window.setInterval(()=>{const n=document.querySelector('.focus-bar span');if(n)n.textContent=`专注中 · ${focusElapsed()}`},1000);render()}
async function finishFocus(){if(!focusStarted)return;window.clearInterval(focusTimer);const started=focusStarted,minutes=Math.max(1,Math.round((Date.now()-started.getTime())/60000));focusStarted=null;await db!.from('focus_sessions').insert({space_id:space.id,owner_id:me(),task_id:focusTask,started_at:started.toISOString(),ended_at:new Date().toISOString(),duration_minutes:minutes});if(focusTask)await db!.rpc('increment_task_actual_minutes',{task_uuid:focusTask,minutes_to_add:minutes});focusTask=null;await load();render()}
async function scheduleNotifications(){if(!Capacitor.isNativePlatform())return;const permission=await LocalNotifications.checkPermissions();if(permission.display==='prompt')await LocalNotifications.requestPermissions();const pending=tasks.filter(t=>t.reminder_at&&new Date(t.reminder_at)>new Date()&&(!t.assignee_id||t.assignee_id===me())).slice(0,50);if(!pending.length)return;await LocalNotifications.schedule({notifications:pending.map(t=>({id:Math.abs(hash(t.id)),title:'研序提醒',body:t.title,schedule:{at:new Date(t.reminder_at)},extra:{taskId:t.id}}))})}
function hash(value:string){let result=0;for(const char of value)result=((result<<5)-result+char.charCodeAt(0))|0;return result||1}
